name: Build Kamus Bahasa Moy App and Upload to GitHub Releases

on:
  push:
    tags:
      - 'v*'  # Trigger this workflow on version tag pushes (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'  # Specify the Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK file to match app name and version
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/kamus-bahasa-moy-${GITHUB_REF##*/}.apk
        shell: bash

      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/kamus-bahasa-moy-${GITHUB_REF##*/}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
